### ISSUE TITLE
运行demo遇到问题

### ISSUE THREAD

**Issue by yanxinmiao** [wswenyue/channelHelper#2]
运行demo时， out文件夹只生成一个apk文件：appName--release-v0.1.2.0-120-20170330
而demo中channel.txt里不是有四个渠道吗 ？？

仔细看了下，运行时有IOException了

`googleplay
java.io.IOException: ÎÄ¼þÃû¡¢Ä¿Â¼Ãû»ò¾í±êÓï·¨²»ÕýÈ·¡£
        at java.io.WinNTFileSystem.canonicalize0(Native Method)
        at java.io.WinNTFileSystem.canonicalize(WinNTFileSystem.java:428)
        at java.io.File.getCanonicalPath(File.java:618)
        at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1076)
        at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1040)
        at com.meituan.android.walle.commands.WriteChannelCommand.parse(WriteCha                                                                                                                                                             nnelCommand.java:50)
        at com.meituan.android.walle.Main.main(Main.java:49)
----ok1_googleplay
`

**Comment by wswenyue** [comment]
里面的所有apk文件和jks文件需要替换成你自己的。config.sh 文件中需要修改自己的相关配置信息

**Comment by Zxhua** [comment]
该替换的文件都替换了，还是出现这个IoException

**Comment by wswenyue** [comment]
@yanxinmiao @Zxhua 我更新了2.0版本。可以试试看。demo可以直接运行的。
